[project]
name = 'resow'
description = 'resow project'
version = '1.0'
readme = 'README.md'
dependencies = ['ee', 'geopandas', 'osgeo', 'numpy']

[build-system]
build-backend = 'flit_core.buildapi'
requires = ['flit_core >=3.2,<4']