name: resowrs
channels:
  - defaults
  - conda-forge
dependencies:
  - earthengine-api=0.1.236
  - gdal=2.3.3
  - geopandas=0.6.1
  - geojson=2.5.0
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.2
  - python=3.8
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - simplekml=1.3.6
  - sphinx=4.4.0
  - sphinx_rtd_theme=1.0.0
