name: resow
channels:
  - defaults
  - conda-forge
dependencies:
  - earthengine-api=0.1.236
  - gdal=2.3.3
  - geopandas=0.4.1
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - numpy=1.22.4
  - pandas=1.3.5
  - python=3.8
  - scikit-image=0.16.2
  - scikit-learn=0.20.3
  - scipy=1.7.3
  - sphinx=4.4.0
  - sphinx_rtd_theme=1.0.0
